### ISSUE TITLE
Alert: SQL giving wrong data

### ISSUE THREAD

**Issue by ebobtron** [ebobtron/Speller-BigBoard#53]
SELECT id, grp, name, min(total) as total, dload, tcheck, size, unload, mem, typ 
    FROM leader_board  WHERE grp = :grp3 GROUP by name, typ ORDER BY total

for data  the results is the min of all columns  

    118 	3 	AndyJudkis 	0.2006 	0.0918 	0.1048 	0 	0.0085 	53.4064 	Trie
    117 	3 	AndyJudkis 	0.2767 	0.0973 	0.1085 	0 	0.07 	39.2093 	Trie
result

    117 	3 	AndyJudkis 	0.2006 	0.0973 	0.1085 	0 	0.07 	39.2093 	Trie

I was so proud of this sql string 
Brian any ideas

**Comment by ebobtron** [comment]
I have a working statement,  pretty sure.

    $sql = "SELECT s.id, s.name, s.total from leader_board s ".
           "JOIN (SELECT min(total) AS total FROM leader_board ".
           "GROUP BY name, typ) min ON s.total = min.total order by total";

crap is, I do not understand this  ` min ON s.total = min.total `  hate using stuff I don't understand

**Comment by theB264** [comment]
What exactly do you need here?  You could 
``` sql
SELECT id, grp, name, MIN(total) as best_time, total, dload, tcheck, size, unload, mem, typ
FROM leader_board  WHERE grp = :grp3 GROUP by name, typ ORDER BY total`

**Comment by ebobtron** [comment]
Hi Brian,
Your example looks like my original above:   Thanks
```sql    
SELECT id, grp, name, MIN(total) as best_time, total, dload, tcheck, size, unload, mem, typ
FROM leader_board  WHERE grp = :grp3 GROUP by name, typ ORDER BY total
```
This below here actually works and I now have a sense of how the `ON` works.
```sql
SELECT s.* from leader_board s JOIN (SELECT min(total) AS total FROM leader_board 
GROUP BY name, typ) min ON s.total = min.total order by total
```
result is now this:

    118     3   AndyJudkis  0.2006  0.0918  0.1048  0   0.0085 53.4064    Trie

instead of the best time and smallest numbers of the two rows

    117     3   AndyJudkis  0.2006  0.0973  0.1085  0   0.07   39.2093    Trie

**Comment by theB264** [comment]
With two tables in the FROM clause, you get a result containing a cartesian product of every possible combination of the two.  The ON clause limits those results to just the ones you want to compare

**Comment by ebobtron** [comment]
Thanks Brian, that helps the comfort level, seems to work well, deployed just now take a peek we have "all" submissions and the fastest of each type for an individual "unique"

issue close code deployed.
